name: Publish CI

on:
  push:
    paths:
      - '**'
      - '!**/README.md'
      - '!.gitpod*'
    tags:
      - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip CI')"
    steps:

      - uses: actions/checkout@v2
        name: Check out source code

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Apply NPM registry credentials
        run: npm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_TOKEN}}"

      - name: Run the publish procedure
        run: npm run deploy

